### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/core-samples-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Multicore programming

- [ ] hello_core&#x2F;main.c uses multicore_launch_core1 to launch second core&#39;s operations
- [ ] single_core_conditions&#x2F;main.c implements the three convert functions
- [x] single_core_conditions&#x2F;main.c implements ADC control over device hardware
- [ ] core_conditions_buffer&#x2F;main.c contains the multicore_fifo_push_blocking function
- [ ] core_conditions_buffer&#x2F;main.c contains the multicore_fifo_pop_blocking function
- [ ] core_conditions_buffer&#x2F;main.c contains the multicore_fifo_rvalid function
- [ ] core_conditions_buffer&#x2F;main.c clears the interrupt buffer twice
- [ ] core_conditions_buffer&#x2F;main.c sets an interrupt handler
- [ ] core_conditions_buffer&#x2F;main.c enables the interrupt handler
- [ ] core_conditions_functions&#x2F;main.c contains sufficient multicore_fifo_push_blocking calls
- [ ] core_conditions_functions&#x2F;main.c contains sufficient multicore_fifo_pop_blocking calls
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c contains the multicore_fifo_push_blocking function
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c contains the multicore_fifo_pop_blocking function
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c contains the multicore_fifo_rvalid function
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c clears the interrupt buffer twice
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c sets an interrupt handler
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c enables the interrupt handler
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c contains the multicore_fifo_push_blocking function
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c contains the multicore_fifo_pop_blocking function
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c contains the multicore_fifo_rvalid function
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c clears the interrupt buffer twice
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c sets an interrupt handler
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c enables the interrupt handler

## TODOs

- [ ] hello_core&#x2F;main.c contains no TODOs
- [ ] single_core_conditions&#x2F;main.c contains no TODOs
- [ ] core_conditions_buffer&#x2F;main.c contains no TODOS
- [ ] core_conditions_functions&#x2F;main.c contains no TODOS
- [ ] core_conditions_buffer&#x2F;main.c contains no TODOS
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c contains no TODOS
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c contains no TODOS
- [ ] docs&#x2F;report.md contains no TODOs

## Timing

- [ ] single_core_conditions&#x2F;main.c uses gettimeofday to calculate start and end times of code section of interest
- [ ] core_conditions_buffer&#x2F;main.c uses gettimeofday to measure code section performance
- [ ] core_conditions_functions&#x2F;main.c uses gettimeofday to measure code section performance
- [ ] core_principles&#x2F;multi_core&#x2F;buffer&#x2F;main.c uses gettimeofday to measure code section performance
- [ ] core_principles&#x2F;multi_core&#x2F;functions&#x2F;main.c uses gettimeofday to measure code section performance

## Memory Management

- [ ] core_conditions_functions&#x2F;main.c contains a struct definition
- [ ] core_conditions_functions&#x2F;main.c contains at least one call to malloc
- [ ] core_conditions_functions&#x2F;main.c measures remaining heap space

## Casting

- [ ] core_conditions_functions&#x2F;main.c uses uint type to characterize function addresses data values
- [ ] core_conditions_functions&#x2F;main.c contains at least one uint cast

## Percent complete

Based on the checks achieved, this assignment is `2%` complete.
